### ISSUE TITLE
about GPU

### ISSUE THREAD

**Issue by zxf8876983** [Momilijaz96/MMT_for_NCRC#3]
hello, coud you tell me how many GPUs i need for this work, please.

**Comment by Momilijaz96** [comment]
hi,
I used a V100 with 32G of RAM, depends on ur budget.

**Comment by zxf8876983** [comment]
Thanks for your answer, i plan to train a similar project, would you mind let me know how long did you train the project with a V100.

**Comment by zxf8876983** [comment]
> hi, I used a V100 with 32G of RAM, depends on ur budget.
Thanks for your answer, i plan to train a similar project, would you mind let me know how long did you train the project with a V100.

**Comment by Momilijaz96** [comment]
For the epochs mentioned in the paper.
Momal Ijaz,
Machine Learning Engineer, Super.ai <http://super.ai/>
e: ***@***.***
p: +92-347907-5154
